@host=http://localhost:3099

GET {{host}}/subscribers/

###
GET {{host}}/subscribers/5ecb3acb9cdaa32de0e12be2 http/1.1
# @name

###
# @name login

#https://blog.novanet.no/rest-client-for-visual-studio-code-auth/


###
POST {{host}}/subscribers/
Content-Type: "application/json"

{
	"name":"Kyle",
	"subscribedToChannel":"Web"
}


###

DELETE {{host}}/subscribers/5ecb3acb9cdaa32de0e12be2 http/1.1

PATCH {{host}}/subscribers/5ecbb038fd708ffbbeced885 HTTP/1.1
Content-Type: "application/json"

{
	"name": "CDE"
}